build.gradle
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/AdminRoutesFactory.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotProperties.kt
envoy-control-tests/build.gradle
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/AdminRouteTest.kt

Adds a new, optional mechanism for securing Envoy admin. When `envoy-control.envoy.snapshot.routes.admin.disable.on-header` is set to X, all requests with header X present will be denied access to admin routes. Access is denied by sending an immediate response with status code configured under `envoy-control.envoy.snapshot.routes.admin.disable.response-code`, by default `403`.
No docs for this change since there are no docs for admin routes at all.

Disable admin when request contains the configured disable header

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/EnvoySnapshotFactory.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotsVersions.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/EnvoyControlTestConfiguration.kt

When EC is starting it should have random RDS version rather than `empty` because new routes will be sent only when Cluster change. Currently if we change something in ingress routes and deploy new version all envoys which don't have dependencies to clusters won't receive updates untill we restart them. This fix should update version each time new version of EC is deployed.

Changed initial RDS version to random

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ControlPlane.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/server/ServerProperties.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/server/callbacks/LoggingDiscoveryServerCallbacks.kt

Every request contains full metadata which is hard to analyze. Change to log: id, cluster, version, nonce, and type or full request when flag is set.

Log full request on flag to make logs easier to analyze

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ControlPlane.kt
envoy-control-runner/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/infrastructure/ControlPlaneConfig.kt
envoy-control-runner/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/debug/SnapshotDebugController.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/SnapshotDebugTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/EnvoyControlTestApp.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EnvoyAdmin.kt

The debugging endpoint uses a textual representation. It's simple enough for a human to parse when debugging issues with a particular Envoy to compare what the control plane knows about it's configuration served via XDS. AutoValues make it difficult to map to JSON so I didn't want to over-engineer it.

Added snapshot debugging endpoint

---

build.gradle
envoy-control-runner/build.gradle
envoy-control-runner/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/debug/SnapshotDebugController.kt
envoy-control-runner/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/debug/SnapshotDebugInfo.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/SnapshotDebugTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/EnvoyControlTestApp.kt

* show xDS versions in the same format as in Envoy metrics (/stats)
* json output
example response:
```json
{
"versions": {
"clusters": {
"raw": "f57c5fd274a946e8b31697b420a83895",
"metric": "8397944043068236980"
},
"listeners": {
"raw": "empty",
"metric": "11940367550976402267"
},
"routes": {
"raw": "f57c5fd274a946e8b31697b420a83895",
"metric": "8397944043068236980"
},
"endpoints": {
"raw": "e379fcc12d94474dbc24210a4bc94857",
"metric": "8333465023560272944"
}
},
"snapshot": {
"clusters": {
// snapshot content
}
// snapshot content
}
```

debugging: /snapshot endpoint enhancements

---

build.gradle

It should fix the problem:
> repository x (in 'open' state) is in transition. Check again later.'. Giving up. Configure longer timeout if necessary.
1 retry takes approximately 7.4 second
So we increase timeout from ~2 minutes to ~6 minutes

Increase number of retries when publishing release artifact to nexus

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/GlobalServiceChanges.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/utils/ReactorUtils.kt

Add helper method for Flux to periodically check and log suppressed error on subscriber.
We know that operator combineLatest sometimes fails, sends cancel() to upstream but doesn't propagate error, so we don't see what happended. This change should make the error visible.

log combineLatest suppressed error

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/GlobalServiceChanges.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/SyncProperties.kt
envoy-control-runner/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/infrastructure/ControlPlaneConfig.kt

Fix for combineLatest() flux operator, that sometimes fails silently and sends cancel to an upstream.
We detected that after the fail, the combineLatest operator has an Exception saved internally, but not propagated to a downstream. The exception is:
> reactor.core.Exceptions$OverflowException: Queue is full: Reactive Streams source doesn't respect backpressure
This is an experimental fix for this problem, which has to be yet verified to decide if it helps with the problem. Hence it is disabled by default and enabled by flag.

GlobalServiceChanges - experimental combineLatest flow fix

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotUpdater.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/CrossDcServiceChanges.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/CrossDcServices.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/GlobalServiceChanges.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/CrossDcServicesTest.kt
envoy-control-services/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/services/ServiceChanges.kt
envoy-control-source-consul/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/consul/services/ConsulLocalServiceChanges.kt

This is the first step of refactoring. The next ones will transform sets and lists of `LocalityAwareServicesState` into a more cohesive and comprehensible suite of names.

#110 List of LocalityAwareServicesState instead of Set

---

envoy-control-services/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/services/ClusterState.kt
envoy-control-services/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/services/MultiClusterStateTest.kt

When `MultiClusterState` does not implement equals then every change from remote DC is treated as a different one, even if it's not. This fixes this problem.

Fix MultiClusterState

---

envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/InternalRedirectTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/LocalServiceCustomHealthCheckRouteTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OriginalDestinationTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OutgoingPermissionsTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OutlierDetectionTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ParallelSnapshotForGroupsTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/RegexServicesFilterTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ServiceTagsAndCanaryTestBase.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/assertions/ResponseAssertions.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/BaseEnvoyTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/EnvoyControlTestConfiguration.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/consul/ConsulExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/consul/ConsulOperations.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/consul/ConsulSetup.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/echo/EchoContainer.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/echo/EchoServiceExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/echo/ServiceContainer.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/echo/ServiceExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EgressOperations.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EnvoyExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/redirect/RedirectServiceContainer.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/reliability/ConsulRpcLimitReachedTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/reliability/DcCutOffTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/reliability/LocalConsulAgentDownTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/reliability/LocalConsulAgentToMasterCutOff.kt

This PR migrates 8 additional tests to the new approach presented in #143.
10 tests in total are migrated at the moment. Their execution time since the migration to the new approach changed from 2m10s to 3m 11s (46% increase). My next task will be to share containers between test classes and to bring the execution time below the original 2m10s.

Migrates more tests to the new approach

---

envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/EnvoyControlSynchronizationTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/HostHeaderRewritingTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/InternalRedirectTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/LocalServiceCustomHealthCheckRouteTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OriginalDestinationTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OutgoingPermissionsTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OutlierDetectionTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ParallelSnapshotForGroupsTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/RegexServicesFilterTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/RetryPolicyTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ServiceTagsAndCanaryTestBase.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ServiceTagsTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/assertions/ResponseAssertions.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/BaseEnvoyTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/EnvoyControlTestConfiguration.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/consul/ConsulOperations.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/CallStats.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EgressOperations.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EnvoyAdmin.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EnvoyExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/ResponseWithBody.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/EchoContainer.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/EchoServiceExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/HttpsEchoContainer.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/RedirectServiceContainer.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/ServiceContainer.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/ServiceExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/reliability/ConsulInstancePropagationTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ssl/EnvoyHttpsDependencyTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ssl/EnvoySANValidationTest.kt

Repackaging in the test sources:
* `echo` package becomes `service`.
* `RedirectServiceContainer` goes to `service`.
`echo` package already contained configuration relating to test services in general, not only the echo service.

Renames config.echo package to config.service

---

envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/InternalRedirectTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OutlierDetectionTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/RetryPolicyTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ServiceTagsAndCanaryTestBase.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/assertions/ResponseAssertions.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/consul/ConsulExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/consul/ConsulOperations.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EgressOperations.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EnvoyExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoycontrol/EnvoyControlExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/EchoServiceExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/GenericServiceExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/service/ServiceExtension.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/sharing/ContainerPool.kt

This PR introduced sharing some of the containers between test classes:
* `ConsulExtension` creates a single shared Consul container instance for all the tests. This extension can only be created once in a test class at the moment.
* `EchoServiceExtension` uses `ContainerPool` to reuse echo containers between the tests. `EchoServiceExtension` can be defined multiple times in a single test class.
The execution time for 10 tests went down from `3m 11s` to `1m 36s`. It was `2m 10s` in the old approach with base classes instead of extensions.
`ContainerPool` currently only supports pooling containers that have no configuration, that is container instances don't differ. This can be developed further in the future. Once we migrate tests that require multiple `ConsulExtension` instances we …

Pooling containers between tests

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/endpoints/EnvoyEndpointsFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotUpdaterTest.kt

Let's say we have 2 instances of EC in the remote cluster. 
First instance on endpoint `state` returns:
```
{
"serviceNameToInstances":
{
"echo":
{
"serviceName":"echo","instances":[]
}
}
}
```
Second instance on endpoint `state` returns:
```
{
"serviceNameToInstances": {}
}
```
And one instance of EC in a local cluster with the state:
```
{
"serviceNameToInstances":
{
"echo":
{
"serviceName":"echo","instances":[]
}
}
}
```
When local instance synchronizes with the first instance in the remote cluster it generates EDS configuration:
```
"clusterName": "echo",
"endpoints": [
{
"locality": {
"zone": "local"
}
},
{
"locality": {
"zone": "remote"
},
"priority": 1
}
]
```
but if it reconnects to the second cluster in remote configuration will change to:
```
"clusterName": "echo",
"endpoints": …
```

Fix unnecessary EDS responses when state between services is inconsistent

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/RemoteClusterStateChanges.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/RemoteServices.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/synchronization/RemoteServicesTest.kt

A state between instances of EC can change. If one instance of EC in remote dc has different state than another one it might trigger cross-cluster changes.
Instance 1 state
```
{
"serviceNameToInstances":
{
"echo":
{
"serviceName":"echo","instances":[(instance ./.....)]
},
"echo2":
{
"serviceName":"echo","instances":[]
}
}
}
```
Instance 2 state
```
{
"serviceNameToInstances":
{
"echo":
{
"serviceName":"echo","instances":[(instance ./.....)]
}
}
}
```
The state is the same because there is no instances of `echo2` in both instances so we shouldn't trigger any changes.
To avoid that we should filter out services with empty `ServiceInstances` to avoid triggering changes. That shouldn't affect local cluster state and problem with removing clusters because once we have service in LocalState …

When fetching state from remote ignore services without instances don't trigger cross dc change

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroup.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadataValidator.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/EnvoySnapshotFactory.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/clusters/EnvoyClustersFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroupTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadataTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/TestNodeFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotUpdaterTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotsVersionsTest.kt

You can specify timeouts for wildcard dependency and override it for specified services
```
metadata:
proxy_settings:
outgoing:
dependencies:
- service: "*"
timeoutPolicy:
idleTimeout: 400
requestTimeout: 800
- service: "slow-service-A"
timeoutPolicy:
idleTimeout: 800
requestTimeout: 1500
- service: "slow-service-B"
timeoutPolicy:
idleTimeout: 800
requestTimeout: 1500  
```

Timeouts for wildcard dependency

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/EnvoySnapshotFactory.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/clusters/EnvoyClustersFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadataTest.kt

PR https://github.com/allegro/envoy-control/pull/165 changed how EC handles duplicates in dependencies list. EC throws exception when this case occurs. This PR reverts to previous behaviour: Dependencies for same serviceName/domainUrl will be deduplicated and last one remain.
```yaml
metadata:
proxy_settings:
outgoing:
dependencies:
- service: "service-A"
timeoutPolicy:
idleTimeout: "10s"
requestTimeout: "8s"
- service: "service-A"
```

Deduplicate dependencies

---

envoy-control-tests/src/main/resources/envoy/bad_config.yaml

`SnapshotUpdaterBadConfigTest` is supposed verify that EC is resilient to Envoy sending invalid proxy settings. Due to wrong YAML indentation the badly configured Envoy did not cause any invalid proxy settings to reach EC, instead failing to start at all.

makes SnapshotUpdaterBadConfigTest pass for the right reasons

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/EnvoyListenersFactory.kt
envoy-control-core/src/main/resources/lua/ingress_client_name_header.lua

Inject TLS inspector explicitly and add envoy_on_response function to remove two warnings from envoy logs

Remove warnings from Envoy logs

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroup.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadataValidator.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/EnvoySnapshotFactory.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotProperties.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyIngressRoutesFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroupTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadataValidatorTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyIngressRoutesFactoryTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/LocalServiceTest.kt
envoy-control-tests/src/main/resources/envoy/config_xds.yaml

Require service-name in request fixes: https://github.com/allegro/envoy-control/issues/91

Add service name and destination header to response

---

envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/clusters/EnvoyClustersFactory.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/RBACFilterFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/rbac/RBACFilterFactoryJwtTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/rbac/RBACFilterFactoryTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/rbac/RBACFilterFactoryTestUtils.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/IngressOperations.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/permissions/IncomingPermissionsOriginalDestinationTest.kt

Adding new rules to rbac filter. Allowed clients should not be blocked, when they are using envoy-original-destination.

Rbac allow original destination

---

CHANGELOG.md
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotProperties.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyEgressRoutesFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/RoutesAssertions.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyEgressRoutesFactoryTest.kt

closes allegro-internal/flex-roadmap#476

Added response header for traffic splitting feature

---

CHANGELOG.md
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/clusters/EnvoyClustersFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/clusters/EnvoyClustersFactoryTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/ClusterCircuitBreakerDefaultSettingsTest.kt

This flag is needed for correct calculation of weights during load balancing (when two configs are present - localityLbConfig and subsetConfig)

Added setting localityAware flag on subsetConfig for clusters with traffic splitting 

---

CHANGELOG.md
build.gradle
envoy-control-core/src/main/java/pl/allegro/tech/servicemesh/envoycontrol/SimpleCache.java
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/GroupChangeWatcher.kt
envoy-control-core/src/test/java/pl/allegro/tech/servicemesh/envoycontrol/v3/SimpleCacheTest.java
envoy-control-core/src/test/java/pl/allegro/tech/servicemesh/envoycontrol/v3/SimpleCacheWithMissingEndpointsTest.java
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotUpdaterTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/OutlierDetectionTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/envoy/EnvoyContainer.kt
tools/envoy/Dockerfile

same update with SimpleCache removed in [this PR](https://github.com/allegro/envoy-control/pull/421)
SimpleCache is a class that was copied from java-control-plane to add some custom logic - this logic is now in java-control-plane, but for safety I am leaving it in separate PR.

java control plane 1.0.45

---

CHANGELOG.md
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/JwtFilterFactory.kt

https://github.com/allegro/envoy-control/pull/419 introduced a problem with lds cache - presumably there was a race condition in building JwtProvider configuration.
Now JwtProviders are built early and specific configuration of them is sent based on envoy proxy version.

fix jwt impacting lds cache

---

CHANGELOG.md
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/Groups.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroup.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/SnapshotProperties.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/CompressionFilterFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroupTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadataTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/TestNodeFactory.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/CompressionFilterTest.kt
envoy-control-tests/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/config/EnvoyControlTestConfiguration.kt
envoy-control-tests/src/main/resources/envoy/config_xds_compression.yaml

closes https://github.com/allegro-internal/flex-roadmap/issues/687

Added compression properties to node metadata 

---

CHANGELOG.md
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/Groups.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroup.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/EnvoySnapshotFactoryTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroupTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/TestNodeFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/LuaFilterFactoryTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyIngressRoutesFactoryTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/utils/GroupsOperations.kt

Added `service_id` to filter metadata. https://github.com/allegro-internal/flex-roadmap/issues/644
- If `service_id` is present in node metadata it will be passed to the filters metadata.
- If missing, the `service_id` value will be empty.

Add service_id to filter metadata

---

CHANGELOG.md
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/Groups.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadata.kt
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/listeners/filters/HttpConnectionManagerFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/EnvoySnapshotFactoryTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/MetadataNodeGroupTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/NodeMetadataValidatorTest.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/TestNodeFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/utils/GroupsOperations.kt

Path normalization as proxy settings field. We keep old api until migration is finished

path normalization as proxysettings field

---

CHANGELOG.md
envoy-control-core/src/main/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyIngressRoutesFactory.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/groups/RoutesAssertions.kt
envoy-control-core/src/test/kotlin/pl/allegro/tech/servicemesh/envoycontrol/snapshot/resource/routes/EnvoyIngressRoutesFactoryTest.kt

Add separated route for path with /status/ prefix and set high priority for it

create separrated status route with high priority
